name:                websockets-control-core
version:             0.1.0.0
homepage:            https://github.com/ChaosGroup/websockets-control
license:             MIT
author:              "Tsvetan Ovedenski"
maintainer:          "dev@tsovedenski.com"
copyright:           "Copyright 2023 Chaos Software OOD"

synopsis:            Interact with other websocket connections
category:            Network

description:
  Utilies that make interaction with other websocket connections easier.
  With this you can have one client send messages to other clients.
  You can also detect when a new client has connected or disconnected.

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- aeson
- async
- containers
- safe-exceptions
- time
- unagi-chan
- websockets

default-extensions:
- DerivingStrategies
- RecordWildCards

library:
  source-dirs: src
  language: GHC2021

ghc-options:
- -Wall
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
